# Generated by Django 6.0 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_tenant", "0002_user_phone_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport_series",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
