# Generated by Django 6.0 on 2026-04-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_tenant", "0004_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("manager", "Manager"), ("seller", "Seller")], max_length=20)),
                ("permission", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_permissions", to="auth_tenant.tenant")),
            ],
            options={
                "db_table": "role_permissions",
                "unique_together": {("tenant", "role", "permission")},
            },
        ),
    ]
