# Generated by Django 6.0 on 2026-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenant', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', '-created_at'], name='clients_tenant__fb2654_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_phone_per_tenant'),
        ),
    ]
