# Generated by Django 6.0.3 on 2026-04-22 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_tenant", "0011_alter_district_id_alter_region_id"),
        ("clients", "0004_alter_client_communication_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_groups",
                        to="auth_tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "client_groups",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="clients", to="clients.group"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["tenant", "-created_at"], name="client_grou_tenant__3d7f55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_group_name_per_tenant"
            ),
        ),
    ]
