# Generated by Django 6.0 on 2026-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenant', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', '-created_at'], name='products_tenant__954819_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('tenant', 'sku'), name='unique_sku_per_tenant'),
        ),
    ]
