# Generated by Django 6.0.3 on 2026-04-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpurchase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productpurchase',
            new_name='product_pur_product_012bc9_idx',
            old_name='product_pur_product_0cae64_idx',
        ),
        migrations.RemoveField(
            model_name='productpurchase',
            name='currency',
        ),
    ]
