# Generated by Django 6.0.3 on 2026-05-11 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenant', '0012_dynamic_roles'),
        ('clients', '0006_remove_client_communication_language'),
        ('sales', '0004_sale_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', '-created_at'], name='sales_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'payment_type'], name='sales_tenant_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['client'], name='sales_client_idx'),
        ),
    ]
